# 	The Make Utility
#	^^^^^^^^^^^^^^^^
# 	1) If you run, use make. This program will look for a file named makefile in your directory, and then execute it.
# 	2) If you have several makefiles, then you can execute them with the command: "make -f Makefile-1"
#	Note: There are several other switches to the make utility. For more info, man make

#	The basic Makefile
#	^^^^^^^^^^^^^^^^^^
all:
	g++ main.cpp hello.cpp factorial.cpp -o hello
